sudo: required
dist: trusty

language: node_js
node_js: "10"

matrix:
  include:
    - name: "macOS"
      os: osx

    - name: "Windows 64"
      os: windows

    - name: "Windows 32"
      os: osx
      script: npm run dist32

    - name: "Linux"
      os: linux  


cache:
  directories:
    - node_modules
    
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

install:
  - nvm install 10
  - npm install electron-builder

script:
  - npm run dist

notifications:
  email: false