sudo: required
dist: trusty

language: node_js
node_js: "10"

matrix:
  include:
    - name: "macOS"
      os: osx
    - name: "Windows 64"
      os: windows
    - name: "Windows 32"
      os: windows
      script: npm run dist32
    - name: "Linux"
      os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang   


cache:
  directories:
    - node_modules   

install:
  - nvm install 10
  - npm install electron-builder

script:
  - npm run dist

notifications:
  email: false