name: Suggestion
description: Use this form to suggest features or improvements for Blockbench
title: "[Suggestion] Suggestion summary"
body:
- type: markdown
  attributes:
    value: |
      **Before submissing a suggestion, please check if it has already been suggested.**
- type: textarea
  id: details
  attributes:
    label: Detailed description of your suggestion
  validations:
    required: true